CREATE TABLE IF NOT EXISTS images(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(256) NOT NULL UNIQUE,
    thumbnail VARCHAR(256) NOT NULL UNIQUE,
    title VARCHAR(32) DEFAULT NULL,
    description VARCHAR(256) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);